local dir = os.getenv('HOME') .. '/.config/awesome/theme/icons'

return {
    -- tags
    terminal = dir .. '/terminal.svg',
    chrome = dir .. '/chrome.svg',
    code = dir .. '/code.svg',
    folder = dir .. '/folder.svg',
    feather = dir .. '/feather.svg',
    music = dir .. '/music.svg',
    graphics = dir .. '/droplet.svg',
    -- others
    firefox = dir .. '/firefox.svg',
    social = dir .. '/forum.svg',
    game = dir .. '/google-controller.svg',
    console = dir .. '/console.svg',
    menu = dir .. '/dashboard.svg',
    close = dir .. '/close.svg',
    close_dark = dir .. '/close_dark.svg',
    logout = dir .. '/logout.svg',
    sleep = dir .. '/power-sleep.svg',
    power = dir .. '/power.svg',
    lock = dir .. '/lock.svg',
    restart = dir .. '/restart.svg',
    search = dir .. '/magnify-dark.svg',
    volume = dir .. '/volume-high.svg',
    volume_dark = dir .. '/volume-high-dark.svg',
    brightness = dir .. '/brightness-7.svg',
    chart = dir .. '/chart-areaspline.svg',
    memory = dir .. '/memory.svg',
    harddisk = dir .. '/harddisk.svg',
    thermometer = dir .. '/thermometer.svg',
    uptime = dir .. '/computer.svg',
    plus = dir .. '/plus.svg',
    github = dir .. '/github.svg',
    deviantart = dir .. '/deviantart.svg',
    codeforces = dir .. '/codeforces.svg',
    youtube = dir .. '/youtube.svg',
    reddit = dir .. '/reddit.svg',
    linkedin = dir .. '/linkedin.svg'
}
