#!/bin/sh
ANS=$(printf "Daemon\nFrame\nKill" | rofi -dmenu -i -p 'Emacs' -width 20 -padding 20 -lines 3 -hide-scrollbar -eh 1 -theme "emacs")
case "$ANS" in
	*Daemon) $HOME/Hive/scripts/editor/emacsd;;
	*Frame) $HOME/Hive/scripts/editor/emacsui;;
	*Kill) pkill emacs;;
esac
